<a href="https://colab.research.google.com/github/Aakriti-9/pythonBasics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy (Numerical Python)
- python library used to working with arrays
- it also uses linear algebra, fourier transform, and matrices operations

- why is it diff than list?
  - its because its speed, numpy arrays are stored at one contineous place in memeory, so process can be very efficient and fast.

In [1]:
!pip install numpy


In [2]:
import numpy as np
print(np.__version__)

2.1.3


### Creating an arrays using numpy

In [3]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### Create a NumPy ndarray Objects

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
## 0-D arrays
import numpy as np
arr = np.array(42)
print(arr)

42


In [7]:
## 1-D array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
## 2-D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
## 3-D array
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Check Number of Dimensions in an NumPy Array?

In [10]:
# check Number of dimensions in an NumPy Array?
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
# create an array of 5 dim and verify its dim
import numpy as np
arr = np.array([1,2,3,4], ndmin=64)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1
                                                                2
                                                                3
                                                                4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
number of dimensions : 64


### Access Array Elements

In [12]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2])

3


In [13]:
# 3rd and 4th element added
import numpy as np

arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

7


### Accessing 2-D Array

In [14]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
print('5th element on 2nd row: ', arr[0,1])


5th element on 2nd row:  2


In [16]:
print('second last element on 2nd row', arr[1,3])

second last element on 2nd row 9


Assignment:

- You need to search and explore by yourself about numpy following features:

  - indexing
  - silicing
  - data type
  - array shape and reshape
  - sorting in numpy
  - array search
  - apply filters
  - random number generation
  - array join

In [17]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


In [18]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0, 1]) # (row, column)
print(arr[2, 0])

20
70


Slicing
[start:end]
 - result includes the start index and elcludes the end index.
 [start:end:step]

In [19]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[:5])
print(arr[2:])
print(arr[:])
print(arr[::2])    # every second element
print(arr[::-1])   # reverse

[10 20 30 40 50]
[30 40 50]
[10 20 30 40 50]
[10 30 50]
[50 40 30 20 10]


In [22]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]])
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
arr[1, 1:4]


array([7, 8, 9])

In [33]:
arr[:,2]

array([3, 8])

In [32]:
arr[0:2, 2]

array([3, 8])

In [20]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


In [21]:
print(arr.shape)

(3, 3)


Numpy Data Types
- strings
- integer
- float
- boolean
- complex

one character can be used to refer data type

- i for int
- u for unsigned int
- b for bool
- f for float
- m timedelta
- M for datetime
- S for string

In [36]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int64


In [38]:
arr = np.array(['apple', 'ball', 'cat', 'dog', 'eleph'])
print(arr.dtype)

<U5


In [39]:
# create an array with data type string
arr = np.array([1, 2, 3, 4], dtype = 'S')
print(arr.dtype)

|S1


Numpy Array Shape
- The shape of an array is the number of elements in each dimensions.

In [40]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
arr.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

Joining two arrays

In [42]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


splitting two array

In [43]:
arr1 = np.array([1, 2, 3])
newarr = np.array_split(arr1, 3)
print(newarr)



[array([1]), array([2]), array([3])]


In [44]:
# Search in array

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [45]:
# Sorting in array
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [46]:
arr = np.array((True, False, True, True, False, False))
np.sort(arr)

array([False, False, False,  True,  True,  True])

Filtering of an array

- Getting out some elements from existing array and create new array out of them is called filtering.
- In NumPy, you filter any array ising a boolean index list.
- if value at an index is True that element is contained in the filtered array,
- if the value at that index is False, then the element is excluded from the filtered array.

In [47]:
arr = np.array([41, 42, 43, 44])
x = [False, True, True, False]

newarr = arr[x]
print(newarr)

[42 43]


In [48]:
# Create a filter array that will return only values higher than 42
arr = np.array([41, 42, 43, 44])
x = [False, False, True, True]

newarr = arr[x]
print(newarr)

[43 44]


In [49]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create a filter using a condition
filter = arr > 42

newarr = arr[filter]
print(newarr)


[43 44]


### Random
 To generate a random numbers, we need to import random module

In [50]:
from numpy import random
import numpy as np

In [53]:
x = random.randint(10)
x

8

In [55]:
x = random.rand()
x

0.35954143210446043

In [68]:
# Create a random array
x = random.randint(100, size=(5))
print(x)

[15 65 78 76 62]


In [76]:
from numpy import random
x = random.choice(["paper", "scissor", "rock"])
print(x)

scissor
